// Prevents additional console window on Windows in release, DO NOT REMOVE!!
#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

mod api;
mod files;

use rand::Rng;
use api::{get_user_dir};
use files::config::Config;

// Learn more about Tauri commands at https://tauri.app/v1/guides/features/command
#[tauri::command]
fn greet(name: &str) -> String {
    format!("Hello, {}! You've been greeted from Rust!", name)
}

#[tauri::command]
fn randommessage() -> String {
    let mut rng = rand::thread_rng();
    format!("{} generated by Rust", rng.gen::<u32>())
}

fn main() {

    let conf = Config::new("jnotes");

    tauri::Builder::default()
        .invoke_handler(tauri::generate_handler![
            greet,
            randommessage,
            get_user_dir,
            conf.dir_exists
        ])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
